# Generated by Django 2.1.1 on 2018-09-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=10)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=30)),
                ('carmodel', models.CharField(max_length=30)),
                ('extrainfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('otherinfo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=50)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField(help_text='Must be same or after startdate')),
                ('price', models.SmallIntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('loc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitdate', models.DateTimeField(auto_now_add=True)),
                ('items', models.TextField()),
                ('specinstruct', models.TextField(blank=True)),
                ('imgs', models.ImageField(blank=True, upload_to='')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorname', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleddate', models.DateTimeField()),
                ('driver', models.CharField(max_length=100)),
                ('triptype', models.CharField(choices=[('PD', 'Pickup/Dropoff'), ('DMP', 'Dump Run')], default='PD', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Donor'),
        ),
    ]
