# Generated by Django 2.1.1 on 2018-10-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_pickup_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fblink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='extrainfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Trip'),
        ),
    ]
