# Generated by Django 2.1.1 on 2018-10-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181001_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsortype',
            field=models.CharField(choices=[('MJ', 'Major Sponsor'), ('SP', 'Sponsored by')], default='SP', max_length=2),
        ),
    ]
