# Generated by Django 2.1.1 on 2018-10-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181001_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventdesc',
            field=models.TextField(blank=True),
        ),
    ]
