# Generated by Django 2.1.1 on 2018-10-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20181003_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menuname',
        ),
        migrations.AlterField(
            model_name='page',
            name='tabname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
