# Generated by Django 2.1.1 on 2018-10-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181003_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='callactn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='page',
            name='callbtn',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='page',
            name='callstr',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
