# Generated by Django 2.1.1 on 2018-10-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20181003_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='callbtn',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='page',
            name='callstr',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
