# Generated by Django 2.1.1 on 2018-10-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20181003_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
