# Generated by Django 2.1.1 on 2018-10-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20181003_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('Author', models.CharField(max_length=30)),
                ('Paper', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('blurb', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.IntegerField()),
                ('soctype', models.CharField(choices=[('IN', 'Instagram'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('YT', 'YouTube')], max_length=2)),
            ],
        ),
    ]
