# Generated by Django 2.1.1 on 2018-10-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_article_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Paper',
            new_name='paper',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='blurb',
            field=models.TextField(max_length=1000),
        ),
    ]
