# Generated by Django 2.1.1 on 2018-10-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20181003_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='donblurb',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='volblurb',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='soctype',
            field=models.CharField(choices=[('IN', 'Instagram'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('YT', 'YouTube'), ('SC', 'SnapChat')], max_length=2),
        ),
    ]
