# Generated by Django 2.1.1 on 2018-10-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_dock'),
    ]

    operations = [
        migrations.AddField(
            model_name='dock',
            name='reason',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
