# Generated by Django 2.0.9 on 2018-10-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_testpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
