# Generated by Django 2.0.9 on 2018-10-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_basepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerimg', models.ImageField(upload_to='headerimages/')),
                ('tabname', models.CharField(blank=True, max_length=20)),
                ('url', models.CharField(blank=True, max_length=20)),
                ('headertitle', models.CharField(max_length=50)),
                ('headersubtitle', models.CharField(blank=True, max_length=80)),
                ('callstr', models.CharField(blank=True, max_length=25)),
                ('callbtn', models.CharField(blank=True, max_length=25)),
                ('callactn', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='basepage',
            name='url',
        ),
    ]
