# Generated by Django 2.0.9 on 2018-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20181008_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
