# Generated by Django 2.0.9 on 2018-10-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_basepage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basepage',
            old_name='url',
            new_name='baseurl',
        ),
    ]
