# Generated by Django 2.0.9 on 2018-10-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20181008_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='thriftpage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
    ]
