# Generated by Django 2.0.9 on 2018-10-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_thriftpage_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
        migrations.AddField(
            model_name='wheelsforhopepage',
            name='webpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.WebPage'),
        ),
    ]
