# Generated by Django 2.0.9 on 2018-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('webapp', '0028_auto_20181008_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name_plural': 'Calls To Action'},
        ),
        migrations.AddField(
            model_name='donatepage',
            name='baseurl',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='callactn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='callbtn',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='callstr',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='headerimg',
            field=models.ImageField(blank=True, upload_to='headerimages/'),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='headersubtitle',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='headertitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='tabname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='template_string',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='callbtn',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='callstr',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='BasePage',
        ),
    ]
