# Generated by Django 2.0.9 on 2018-10-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20181010_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='template_string',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
