# Generated by Django 2.0.9 on 2018-10-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20181010_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='headerimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='headerimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='headerimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headerimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='thriftpage',
            name='headerimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='wheelsforhopepage',
            name='headerimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
