# Generated by Django 2.0.9 on 2018-10-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20181010_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='thriftpage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='volunteerpage',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='wheelsforhopepage',
            name='webpage',
        ),
    ]
