# Generated by Django 2.0.9 on 2018-10-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('webapp', '0034_auto_20181010_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerpage',
            name='baseurl',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='callactn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='callbtn',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='callstr',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='headerimg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='headersubtitle',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='headertitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='tabname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
