# Generated by Django 2.0.9 on 2018-10-11 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20181010_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
        migrations.AddField(
            model_name='thriftpage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
        migrations.AddField(
            model_name='volunteerpage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
        migrations.AddField(
            model_name='wheelsforhopepage',
            name='calltoaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.CallToAction'),
        ),
    ]
