# Generated by Django 2.0.9 on 2018-10-11 07:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_auto_20181011_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
