# Generated by Django 2.0.9 on 2018-10-11 08:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_contactpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='test',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
