# Generated by Django 2.0.9 on 2018-10-09 20:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_donatepage_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='test',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('dock', webapp.models.DockBlock())], blank=True),
        ),
    ]
