# Generated by Django 2.0.9 on 2018-10-10 03:57

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import webapp.blocks
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_auto_20181009_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vector', models.FileField(upload_to='icons', validators=[webapp.models.Icon.validatevector])),
            ],
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='test',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('dock_status', webapp.models.DockBlock()), ('loc', webapp.blocks.LocBlock(target_model='webapp.Location')), ('sponsor_grid', wagtail.core.blocks.StructBlock([('sponsor_header_text', wagtail.core.blocks.CharBlock(default='Major Sponsors', help_text='Text on top of Sponsor Grid', max_length=30))])), ('two_panel', wagtail.core.blocks.StructBlock([('LHScontent', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock())], label='Left Hand Side Content, mobile-top')), ('RHScontent', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock())], label='Right Hand Side Content, mobile-bottom'))])), ('map', wagtail.core.blocks.StructBlock([('map_provider', wagtail.core.blocks.ChoiceBlock(choices=[('GM', 'Google Maps'), ('OM', 'Open Street Map')], help_text="Google Maps no longer provides a free embedded map (though it's effectively free if you don't call it in high volume - still needs payment info to get rid of 'development purposes only' overlay). Open Street Maps is free")), ('map_long', wagtail.core.blocks.CharBlock(default=-121.948261, max_length=255, required=True)), ('map_lat', wagtail.core.blocks.CharBlock(default=38.345813, max_length=255, required=True)), ('map_zoom_level', wagtail.core.blocks.CharBlock(default=14, max_length=3, required=True))]))], blank=True),
        ),
    ]
